# Use an official Python runtime as a parent image
FROM python:3.13-slim

# Install network diagnostics utilities
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    netcat-openbsd \
    iputils-ping \
    traceroute \
    dnsutils \
    net-tools \
    telnet \
    && apt-get clean

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY user-management/requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application
COPY user-management/ .

# Expose the port the app runs on
EXPOSE 5000

ENV FLASK_RUN_HOST=0.0.0.0
CMD ["python", "app.py", "--debug",  "--port=5000"]
